services:
  db:
    container_name: db
    image: mysql:9.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - webnet
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend # Monta el código local en el contenedor
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - webnet
  app:
    container_name: app
    build:
      context: ./frontend 
    ports:
      - "8080:8080" 
    working_dir: /app
    volumes:
      - ./frontend:/app           # Monta el código en el mismo WORKDIR
      - /app/node_modules         # Evita sobreescribir los node_modules del contenedor
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true # Importante para que Webpack observe cambios dentro de contenedor
    networks:
      - webnet

networks:
  webnet:

volumes:
  mysql-data: