services:
  db:
    container_name: db
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - backnet
  backend:
    container_name: backend
    build:
      context: ./backend
    volumes:
      - ./backend:/app/backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=pets
      - DB_USER=root
      - DB_PASSWORD=12345
      - DB_HOST=db
      - DB_DIALECT=mysql+pymysql
      - SECRET_KEY=mi_clave
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    networks:
      - frontnet
      - backnet
  app:
    container_name: app
    build:
      context: ./frontend
    volumes:
      - react_build:/app/build
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
  nginx:
      container_name: nginx
      build: 
        context: ./nginx
      ports:
        - "443:443"
      depends_on:
        - app
        - backend
      networks:
        - frontnet
      volumes:
        - ./certbot/conf:/etc/ssl/certs 
        - react_build:/usr/share/nginx/html

networks:
  frontnet:
    driver: bridge
  backnet:

volumes:
  mysql-data:
  react_build: